### PR TITLE
Build: use @grafana/toolkit

### PR DESCRIPTION
**Pull request by ryantxu**
try using @grafana/toolkit

### CODE REVIEW

**Comment by ryantxu** [comment]
@dprokop -- failing with:

image

**Comment by dprokop** [comment]
Seems like a legitimate failure, isn't it? Tests seems to fail on master as well (not caused by typecheck in jest though, but by invariant throwing in slate-plain-serializer - but the root cause is the same - using API that does not exist in that version of plain).

**Comment by daniellee** [comment]
@ryantxu @dprokop I merged in a PR from David and updated here. Tried to run yarn build and got a lot of typing errors (mostly implicit any) and the tests regex failed to find any tests.

**Comment by ryantxu** [comment]
thanks @daniellee -- now I have the errors down to:
image

**Pull request merged**
