### PR TITLE
Respect `$range` in variable evaluation requests

### PR DESCRIPTION
**Pull request by zarbis**
Unlike InfluxQL, Flux allows extracting tag values for specific time range. Right now it's impossible to utilize this feature in Grafana since `$range` in request like this:
```
from(bucket: "analytics")
|> range($range)
|> filter(fn: (r) =>  r._measurement == "foo" )
|> keyValues(keyColumns: ["bar"])
```
is always expanded into hard-coded `start: -1h`.

It leads to confusing and hard-to-pinpoint inconsistencies. For example: 
1) you have table with daily summary of events by their type
2) time picker is set to `Last 7 days`
3) but sums of events are calculated only on types of events that happened only in last hour

This happens due to event types are retrieved from Grafana variable, populated by Flux query. This PR makes Grafana to template correct time range into variable query.

### CODE REVIEW

**Comment by zarbis** [comment]
@davkal PTAL

**Comment by jtlisi** [comment]
LGTM, I will test this tomorrow and try to get it merged.

**Comment by zarbis** [comment]
@jtlisi any progress on this?

**Comment by zarbis** [comment]
@jtlisi humble bump

**Comment by zarbis** [comment]
Anyone?

**Comment by zarbis** [comment]
@davkal PTAL

**Comment by zarbis** [comment]
@jtlisi Still working on this?

**Comment by davkal** [comment]
I think we need @briangann

**Comment by andig** [comment]
Lgtm. What is missing to get this merged?

/cc @daniellee

**Comment by zarbis** [comment]
@daniellee any chance for it to get merged within this year? :)

**Comment by ryantxu** [comment]
@zarbis -- I am going to try to release this in ~1 week.  If there is anything else you are looking at I will have to time to focus on it next week

**Comment by zarbis** [comment]
@ryantxu any progress on this?

**Comment by srclosson** [comment]
Merged into master. Thanks!

**Pull request merged**
